*/*_playlist.ini
#688/688_playlist.ini
#BTI/bti_playlist.ini
#Civ/civ_playlist.ini
#Doom/doom_playlist.ini
#Doom2/doom2_playlist.ini
#Duke/Duke_playlist.ini
#Duke3D/Duke3D_playlist.ini
#EOB/eob_playlist.ini
#HardDriving/HardDriving_playlist.ini
#ISW/isw_playlist.ini
#Lambo_AC/lambo_ac_playlist.ini
#MilleBorne/mb_playlist.ini
#NigelMansell/nmwc_playlist.ini
#PQ1/pq1_playlist.ini
#RRT/rrt_playlist.ini
#RRTD/rrtd_playlist.ini
#SC3/sc3_playlist.ini
#SeaRogue/searogue_playlist.ini
#Starcom/starcom_playlist.ini
#Starcon2/starcon2_playlist.ini
#StuntDriver/sd_playlist.ini
#Stunts/stunts_playlist.ini
#S-ZZT/szzt_playlist.ini
#Tyrian/tyrian_playlist.ini
#WarCraft2/wc2_playlist.ini
#Monopoly/mono_playlist.ini
