*/*_playlist.ini
#Half-Life/halflife_playlist.ini
#Quake3Arena/q3a_playlist.ini
#UnrealTournament/ut99_playlist.ini
#Diablo2/diablo2_playlist.ini
#StarCraft/starcraft_playlist.ini
#AgeOfEmpires2/aoe2_playlist.ini
#DeusEx/deusex_playlist.ini
#NeedForSpeedPorsche/nfspu_playlist.ini
#TheSims/sims_playlist.ini
#Homeworld/homeworld_playlist.ini
