p3_about.txt|10
*/*_playlist.ini
#Descent/descent_playlist.ini
#Descent2/descent2_playlist.ini
#NeedForSpeed2/nfs2_playlist.ini
#NeedForSpeed3/nfs3_playlist.ini
#FreeCell/freecell_playlist.ini
#Doom/doom_playlist.ini
#Doom2/doom2_playlist.ini
#UnRealTournament/urtgoty_playlist.ini
